sudo: required

language: go
go:
  - 1.7

services:
  - docker

cache:
  directories:
    - $HOME/.docker

env:
  - DOCKER_IMAGE=panorama_test

before_install:
  - go get github.com/tonistiigi/buildcache/cmd/buildcache

install:
  - if [ -e $HOME/.docker/latest_image.tar.gz ]; then
      docker load -i $HOME/.docker/latest_image.tar.gz;
    fi
  - if [ -e $HOME/.docker/latest_cache.tar.gz ]; then
      docker load -i $HOME/.docker/latest_cache.tar.gz;
    fi
  - docker-compose --project-name panorama build test
  - docker save $DOCKER_IMAGE | gzip > $HOME/.docker/latest_image.tar.gz
  - sudo `which buildcache` save -o $HOME/.docker/latest_cache.tar.gz $DOCKER_IMAGE
  - sudo chown $USER $HOME/.docker/latest_cache.tar.gz

script:
  - docker-compose run test

